# Site settings
author: Jeffer Hernandez
title: My Software Engineering Journey
header-img: img/home-bg.png
email: softwarejeffhernandez@gmail.com
copyright_name: Jeffer Hernandez
description: > # this means to ignore newlines until "baseurl:"
  Get to know me
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: SoftwareJeff
github_username:  Jeffer-Hernandez

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
